# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI_para.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form_para(object):
    def setupUi(self, Form_para):
        Form_para.setObjectName("Form_para")
        Form_para.resize(444, 222)
        self.gridLayout = QtWidgets.QGridLayout(Form_para)
        self.gridLayout.setObjectName("gridLayout")
        self.area_label = QtWidgets.QLabel(Form_para)
        self.area_label.setObjectName("area_label")
        self.gridLayout.addWidget(self.area_label, 0, 0, 1, 1)
        self.area_line = QtWidgets.QLineEdit(Form_para)
        self.area_line.setObjectName("area_line")
        self.gridLayout.addWidget(self.area_line, 0, 1, 1, 1)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.set_btn = QtWidgets.QPushButton(Form_para)
        self.set_btn.setObjectName("set_btn")
        self.gridLayout_2.addWidget(self.set_btn, 0, 2, 1, 1)
        self.read_btn = QtWidgets.QPushButton(Form_para)
        self.read_btn.setObjectName("read_btn")
        self.gridLayout_2.addWidget(self.read_btn, 0, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem, 0, 1, 1, 1)
        self.gridLayout.addLayout(self.gridLayout_2, 0, 2, 1, 2)
        self.angle_1_label = QtWidgets.QLabel(Form_para)
        self.angle_1_label.setObjectName("angle_1_label")
        self.gridLayout.addWidget(self.angle_1_label, 1, 0, 1, 1)
        self.angle_1_line = QtWidgets.QLineEdit(Form_para)
        self.angle_1_line.setObjectName("angle_1_line")
        self.gridLayout.addWidget(self.angle_1_line, 1, 1, 1, 1)
        self.angle_2_label = QtWidgets.QLabel(Form_para)
        self.angle_2_label.setObjectName("angle_2_label")
        self.gridLayout.addWidget(self.angle_2_label, 1, 2, 1, 1)
        self.angle_2_line = QtWidgets.QLineEdit(Form_para)
        self.angle_2_line.setObjectName("angle_2_line")
        self.gridLayout.addWidget(self.angle_2_line, 1, 3, 1, 1)
        self.len_1_label = QtWidgets.QLabel(Form_para)
        self.len_1_label.setObjectName("len_1_label")
        self.gridLayout.addWidget(self.len_1_label, 2, 0, 1, 1)
        self.len_1_line = QtWidgets.QLineEdit(Form_para)
        self.len_1_line.setObjectName("len_1_line")
        self.gridLayout.addWidget(self.len_1_line, 2, 1, 1, 1)
        self.len_2_label = QtWidgets.QLabel(Form_para)
        self.len_2_label.setObjectName("len_2_label")
        self.gridLayout.addWidget(self.len_2_label, 2, 2, 1, 1)
        self.len_2_line = QtWidgets.QLineEdit(Form_para)
        self.len_2_line.setObjectName("len_2_line")
        self.gridLayout.addWidget(self.len_2_line, 2, 3, 1, 1)
        self.delay_11_label = QtWidgets.QLabel(Form_para)
        self.delay_11_label.setObjectName("delay_11_label")
        self.gridLayout.addWidget(self.delay_11_label, 3, 0, 1, 1)
        self.delay_11_line = QtWidgets.QLineEdit(Form_para)
        self.delay_11_line.setObjectName("delay_11_line")
        self.gridLayout.addWidget(self.delay_11_line, 3, 1, 1, 1)
        self.delay_21_label = QtWidgets.QLabel(Form_para)
        self.delay_21_label.setObjectName("delay_21_label")
        self.gridLayout.addWidget(self.delay_21_label, 3, 2, 1, 1)
        self.delay_21_line = QtWidgets.QLineEdit(Form_para)
        self.delay_21_line.setObjectName("delay_21_line")
        self.gridLayout.addWidget(self.delay_21_line, 3, 3, 1, 1)
        self.delay_12_label = QtWidgets.QLabel(Form_para)
        self.delay_12_label.setObjectName("delay_12_label")
        self.gridLayout.addWidget(self.delay_12_label, 4, 0, 1, 1)
        self.delay_12_line = QtWidgets.QLineEdit(Form_para)
        self.delay_12_line.setObjectName("delay_12_line")
        self.gridLayout.addWidget(self.delay_12_line, 4, 1, 1, 1)
        self.delay_22_label = QtWidgets.QLabel(Form_para)
        self.delay_22_label.setObjectName("delay_22_label")
        self.gridLayout.addWidget(self.delay_22_label, 4, 2, 1, 1)
        self.delay_22_line = QtWidgets.QLineEdit(Form_para)
        self.delay_22_line.setObjectName("delay_22_line")
        self.gridLayout.addWidget(self.delay_22_line, 4, 3, 1, 1)
        self.fixed_temp_label = QtWidgets.QLabel(Form_para)
        self.fixed_temp_label.setObjectName("fixed_temp_label")
        self.gridLayout.addWidget(self.fixed_temp_label, 5, 0, 1, 1)
        self.fixed_temp_line = QtWidgets.QLineEdit(Form_para)
        self.fixed_temp_line.setObjectName("fixed_temp_line")
        self.gridLayout.addWidget(self.fixed_temp_line, 5, 1, 1, 1)
        self.fixed_press_label = QtWidgets.QLabel(Form_para)
        self.fixed_press_label.setObjectName("fixed_press_label")
        self.gridLayout.addWidget(self.fixed_press_label, 5, 2, 1, 1)
        self.fixed_press_line = QtWidgets.QLineEdit(Form_para)
        self.fixed_press_line.setObjectName("fixed_press_line")
        self.gridLayout.addWidget(self.fixed_press_line, 5, 3, 1, 1)

        self.retranslateUi(Form_para)
        QtCore.QMetaObject.connectSlotsByName(Form_para)

    def retranslateUi(self, Form_para):
        _translate = QtCore.QCoreApplication.translate
        Form_para.setWindowTitle(_translate("Form_para", "参数设置"))
        self.area_label.setText(_translate("Form_para", "截面积"))
        self.set_btn.setText(_translate("Form_para", "设置"))
        self.read_btn.setText(_translate("Form_para", "读取"))
        self.angle_1_label.setText(_translate("Form_para", "角度1"))
        self.angle_2_label.setText(_translate("Form_para", "角度2"))
        self.len_1_label.setText(_translate("Form_para", "声程1"))
        self.len_2_label.setText(_translate("Form_para", "声程2"))
        self.delay_11_label.setText(_translate("Form_para", "声延时1-1"))
        self.delay_21_label.setText(_translate("Form_para", "声延时2-1"))
        self.delay_12_label.setText(_translate("Form_para", "声延时1-2"))
        self.delay_22_label.setText(_translate("Form_para", "声延时2-2"))
        self.fixed_temp_label.setText(_translate("Form_para", "固定温度值"))
        self.fixed_press_label.setText(_translate("Form_para", "固定压力值"))
